---
title: "Exemplo R Markdown"
author: "Impacta"
date: "2 de Janeiro de 2024"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

## R Markdown
Esse é um documento **R Markdown**. Site oficial do pacote: <http://rmarkdown.rstudio.com>.

```{r cars}
exemplo <- data.frame("nome" = c("Joana", "Maria", "Joao", "Pedro", "Jose"), 
                      "idade" = c(21, 25, 28, 34, 18), 
                      "qtd_livros" = c(5, 1, 2, 1, 3),
                      "faculdade" = c("Engenharia", "Engenharia", "Direito", "Enfermagem", "Engenharia"), 
                      stringsAsFactors = FALSE)
summary(exemplo)
```

## Gráficos aprendidos em outras lições:

Histograma:

```{r pressure, echo=FALSE}
ggplot(data = exemplo, aes(x = faculdade, fill = faculdade)) +
  geom_bar(stat="count") + 
  coord_flip() +
  xlab("Cursos") +
  ylab("Quantidade total de alunos") +
  ggtitle("Histograma") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))
```

**OBS:** Utilizando `echo = FALSE`, o código utilizado para gerar os resultados não aparece na tela.
